### ISSUE TITLE
`purs bundle`

### ISSUE THREAD

**Issue by i-am-the-slime** [working-group-purescript-es/purescript#1]
Originally written by @thomashoneyman

`purs bundle` works over ES modules, but it needs more work to preserve strict semantics, comments, and code formatting without destroying source maps.

ES modules are supposed to be in strict mode so we should emit a "use strict" directive when bundling them.

We split ES named exports into two statements when bundling: the exported declaration and the assignment to the `exports` object -- ie. `export var decl` becomes `var decl` followed by `exports.decl = decl` -- and while the exported declaration keeps its original position (`export var decl` becomes `var decl`) the comment, attached to the export and not the declaration itself, is lost entirely. We don't preserve comments on imported declarations either. None of this is insurmountable (we "just" have to recompute source annotations with accurate comment and token positions).

We have a few options here:

1. We don't worry about this, and just accept that it's a drawback of the purs bundler that it cannot preserve strict semantics, comments, and code formatting, so that we can ship PureScript 0.15. The upside is that we don't have to work on it, and the downside is...well, these drawbacks.
2. We put some work into our bundler to fix these issues. The upside is that we fix these issues, and the downside is that it's a lot more work on a long-unfinished feature.
3. We drop our bundler altogether and rely on JS bundlers (ie. esbuild) instead. The upside is that we stop sinking work into our homemade bundler and take advantage of all the work done in the JS ecosystem; the downside is that users can no longer bundle with purs alone.

I don't think there's any way the compiler team would accept option (3) for the next PureScript release, but I think it's worth discussing it for the long-term future of the compiler.

There's some discussion here: https://github.com/purescript/purescript/issues/4039#issuecomment-873419028.

**Comment by i-am-the-slime** [comment]
We have been able to reproduce [kl0tl's results](https://github.com/purescript/purescript/issues/4039#issuecomment-873419028) from using esbuild with purity annotations.

Using the following purescript file
```purescript
module Main where

import Prelude

import Effect (Effect)
import Effect.Console (log)

main :: Effect Unit
main = log "Hello world"
```
and the following `run.mjs` 
```js
#!/usr/bin/env node

import { main } from './output/Main/index.js'

main()
```

we can bundle this with the esbuild command 

```bash
esbuild run.mjs --bundle > esbuild-result.js
```
The resulting javascript looks like this:
```js
#!/usr/bin/env node
(() => {
  // output/Effect.Console/foreign.js
  var log = function(s) {
    return function() {
      console.log(s);
    };
  };

  // output/Main/index.js
  var main = /* @__PURE__ */ log("Hello world");

  // run.mjs
  main();
})();
```
Further, we can use the latest version of the google closure compiler that supports inlining of curried functions. It needs to be compiled with the setting described in [this comment](https://github.com/google/closure-compiler/issues/3713#issuecomment-999170951).
(Set `assumeClosuresOnlyCaptureReferences = true` in file `/src/com/google/javascript/jscomp/CompilationLevel.java` in `applyFullCompilationOptions`)

```bash
java -jar compiler_unshaded_deploy.jar -O ADVANCED --js esbuild-result.js --js_output_file final.js
```
 to get the resulting `final.js` file
```js
console.log("Hello world");
```

With regards to bundle size this indicates that we can remove the `purs bundle` functionality.

One remaining question is how to identify impure functions.

**Comment by chrisdone** [comment]
This is a good blog post that details challenges to using Google Closure on real PureScript code: https://www.stefan-fehrenbach.net/blog/2018-02-25-purescript-and-google-closure-notes/index.html

Those would have to be overcome to properly use Google Closure.

**Comment by chrisdone** [comment]
Relatedly, I'm having trouble reproducing the uncurrying result of Google Closure: https://github.com/google/closure-compiler/issues/3713#issuecomment-1002653420

Hopefully, I can get something working with help from the original commenter.

It might be neat to have a GitHub repo like purescript-google-closure that would just have a list of jars of different closure versions compiled with that flag, for easy download and use for purescript bundling.

**Comment by chrisdone** [comment]
I got help reproducing and now have [a working Dockerfile.](https://github.com/chrisdone/google-closure-purescript) I've put it on a repo for my own use, which will help me experiment with PureScript and closure.

**Comment by thomashoneyman** [comment]
A screenshot from @sigma-andex on the PureScript Discord showing bundle sizes with various approaches, with the following note:

> The v14 builds use zephyr, while the v15 dont. `all-esm` means that the dependencies are already using esm modules. The builds with further google closure optimization aren't working.

So we should disregard the closure ones, and look at say `esbuild` alone vs. existing `purs bundle`:

<img width="500" alt="Screenshot_2021-12-28_at_20 39 35" src="https://user-images.githubusercontent.com/10245104/148612971-6ff42981-deac-4fdf-a47f-0a2229a669f4.png">

This gets us:

* 602k for `esbuild` with ES modules
* 692k for `esbuild` run after `purs bundle` using PureScript 0.14
