### ISSUE TITLE
You guys are currently breaking the main compiler repo by committing changes to es-modules branches

### ISSUE THREAD

**Issue by rhendric** [working-group-purescript-es/purescript#16]
I can't build PureScript locally anymore, and CI builds in PRs are also failing, because the compiler repo currently depends on the `es-modules` branches of the repos here and you've committed incompatible things to those branches in the very recent past.

Can we stabilize the situation—roll back all the es-modules branches to where they were when the modules work landed, and do further development on new branches? Or something else? There is a whole lot of move-fast-break-things energy coming out of this group and I appreciate the hustle but it's not great for people not focusing on the ES modules work.

**Comment by JordanMartinez** [comment]
Thanks for bringing this to our attention and sorry about that.

Could you clarify what those recent changes are and where they were made?

I think this is how we should move forward:
- create a new branch `es-modules-continue` that stores the current `es-modules` branch's location in the commit history. I think some people might be using the `es-modules` branches in their projects, so this at least doesn't get in their way.
- revert the recent changes made to `es-modules` branch
- create a separate branch `es-modules-libraries` that stores the work being done for the ecosystem update

**Comment by rhendric** [comment]
Looks like you've figured out at least as much as I knew as of last night—I wasn't aware of exactly how many libraries had been committed to, only that something out of band had started using a syntax the compiler's bundler didn't support, although now it appears that it was just prelude.

The above plan sounds good to me. Thanks for addressing this.
